### ISSUE TITLE
Dependency required: censys.search

### ISSUE THREAD

**Issue by Donotnoanything** [censys/censys-recon-ng#4]
After running commands in the installation part, and use my api key in recon-ng.
The modules reports: 
[!] Module 'recon/domains-hosts/censys_domain' disabled. Dependency required: ''censys.search''.
[!] Module 'recon/hosts-hosts/censys_ip' disabled. Dependency required: ''censys.search''.
[!] Module 'recon/hosts-hosts/censys_hostname' disabled. Dependency required: ''censys.search''.
[!] Module 'recon/companies-contacts/censys_email_address' disabled. Dependency required: ''censys.search''.

Recon-ng version: 5.1.1
OS: parrot os

I think I somehow missed the censys.search dependency?Could you help me with this issus?

**Comment by thehappydinoa** [comment]
Hi @Donotnoanything,

This means you need to update your version of the Censys Python SDK. Run this command to upgrade: `pip install --upgrade censys`

**Comment by saltasatelites** [comment]
Hello,
I have no intention of make cross posting, I've continue a topic in recon-ng (#149) with this issue because  I'm no sure if this problem is with recon-ng, python-censys or python 3.10
I'm running Recon-ng in Archlinux. All the dependencies installed with pacman, and recon-ng compiled from github. 
Python-censys version 2.1.2.
This is the output of the modules that use censys:

 Module 'recon/netblocks-hosts/censys_netblock' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.

Module 'recon/netblocks-companies/censys_netblock_company' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.

Module 'recon/hosts-hosts/censys_hostname' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.

Module 'recon/hosts-hosts/censys_query' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.

Module 'recon/domains-hosts/censys_domain' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.

Module 'recon/companies-hosts/censys_org' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.

Module 'recon/companies-contacts/censys_email_address' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.

Module 'recon/domains-companies/censys_companies' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.

Thanks

**Comment by thehappydinoa** [comment]
Hi @saltasatelites, thank you for reporting this. I am going to create a new issue for this specifically as these are two slightly different issues.
